### ISSUE TITLE
Suggestion: Make the on-screen chat box bigger

### ISSUE THREAD

**Issue by Echostrike36** [DevChatter/StreamInfo#1]
Since the chat is a major part of ChatBot development it may be a good idea to make the on-screen chat box bigger. Right now any game that starts up fills the entirety of the tiny corner chatbox.

This will help those of us who watch the Stream/VoD full screen (!Lurk). Or people who cast the stream to their ChromeCast. Or if you export to Youtube it will be nice to have a serviceable on-screen chatbox.

**Comment by benrick** [comment]
Great point! I'll make sure to make it bigger.
