### ISSUE TITLE
Suggestion: SOLID Stream

### ISSUE THREAD

**Issue by benrick** [DevChatter/StreamInfo#12]
Do a stream where there's an hour spent on each solid principle, explanation and examples.

Guest for each? No guest? One guest?

**Comment by asyncawake** [comment]
I think a guest per letter is fun but it also brings so much variety in teaching methodology that to me it would almost be counterproductive. There would be so much going on and so much to adjust to while simultaneously taking in the principles. I'd rather see you do it all seamlessly in one piece or "pair program/pair teach" it together with one other person.
It would be nice to have simple projects for each principle but in addition also mention examples where the principles are used in the bot project for those familiar with the bot.

**Comment by benrick** [comment]
Yeah, @asyncawake , the thought with multiple guests is that I would be the consistent part of it, but I think it's a great point. And yes, the interesting thing is how well they all interact, so you almost can't show an example of any without talking a bit about each. It happens.
