### ISSUE TITLE
Set stream subscriber/follower/cheers and whatnot goals. 

### ISSUE THREAD

**Issue by asyncawake** [DevChatter/StreamInfo#2]
We're over 500 followers already, maybe a goal for 1000...
You could give away a calendar, or as a bigger goal chose a winner and give him or her an on-stream code review for half an hour...

**Comment by benrick** [comment]
Yep. I was planning on my follower goals being:

- 512 - We celebrated this one with a 5+ hour stream
- 1024 - (thinking about doing a day-long project for this one)
- 2048
- 4096

**Comment by asyncawake** [comment]
Awesome, loving the nerdy numbers!
