### ISSUE TITLE
Special Event 1 - Planning

### ISSUE THREAD

**Issue by benrick** [DevChatter/StreamInfo#5]
Let's use this to plan our first special event.

**Comment by asyncawake** [comment]
Does this refer to the 1024 followers celebration event? Are there any suggestions for it yet? Maybe get @sadukie to hang out? 
Perhaps do a game stream - something out of the ordinary - maybe some indie games or some random c# console games found on github :)

**Comment by benrick** [comment]
Yeah, this is where we're planning the event from our 1024 follower goal.

I am thinking of either doing a workshop, competition, or panel discussion.

Yes, @sadukie and @ardalis are on the short list of guests for either/both of those.
