### ISSUE TITLE
The first video of the bot project is missing on youtube

### ISSUE THREAD

**Issue by asyncawake** [DevChatter/StreamInfo#6]
The very first video from February 12th where you are setting up the first classes etc. is missing. For many beginners watching the stream and being overwhelmed by the architecture, this one would be invaluable to watch. 

In addition or in case the video is definitely lost forever it would be great to have a 30 min or so walkthrough sometime for newbies, detailing how the bot works from the ground up (i.e. whats a chatClient object) etc. This could be a nice intro clip for youtube for those who want to catch up but have less time, as well.

**Comment by pospieszja** [comment]
The same problem :(
https://github.com/DevChatter/StreamInfo/issues/8

**Comment by benrick** [comment]
Is this it? https://youtu.be/Kf7m-_N0YDQ

**Comment by asyncawake** [comment]
Awesome, you found it!!!
It should maybe get this other video's title:
https://www.youtube.com/watch?v=6Ya1mwd6hMo&t=929s
