### ISSUE TITLE
Can't find archive movie - GameTracker

### ISSUE THREAD

**Issue by pospieszja** [DevChatter/StreamInfo#8]
I think Twitch remove old movies from archive. The oldest movie is from 23.04.2018. Is it possible to uploaded it to YT?
I'm looking for first movie about GameTracker (setup solution etc).

**Comment by asyncawake** [comment]
@pospieszja #6 refers to the twitch bot (devchatterbot), or rather the first video for that, not the GameTracker. That video seems to be  remain missing but all other stream videos should be uploaded to youtube soon, including that GameTracker one, I hope. 
Twitch does remove old VODs from their site after a while and they want some exclusivity so there is always some delay until Brendan uploads the videos to youtube.

**Comment by benrick** [comment]
Absolutely possible to find the video!
It is scheduled to go live on Friday, June 22, 2018 and will be here:
https://youtu.be/V4-f0oZV_yw

**Comment by pospieszja** [comment]
Great, I'm looking forward!
